### ISSUE TITLE
Replace 'Foobar' with 'libcsdr' in the license header (line 17 in all the .cpp and .hpp files)

### ISSUE THREAD

**Issue by fventuri** [jketterl/csdr#5]
Jakob,
I noticed that the license header for all the files has the following (lines 16-17):

```
You should have received a copy of the GNU General Public License
along with Foobar.  If not, see <https://www.gnu.org/licenses/>.
```

I think it should be changed with:
```
You should have received a copy of the GNU General Public License
along with libcsdr.  If not, see <https://www.gnu.org/licenses/>.
```

Franco

**Comment by jketterl** [comment]
Thank you for pointing that out. Indeed, I did a lot of copy & paste and didn't pay attention.

I don't normally maintain a license header on every single file in my projects, but the licensing in this project is not straightforward...
